name: rentlens
description: "A camera rental application built with Flutter and Supabase"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.3.4

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.0.2

  # UI
  google_fonts: ^6.1.0
  
  # Utilities
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  flutter_dotenv: ^5.1.0
  uuid: ^4.3.3

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  # Assets
  assets:
    - .env
  #   - assets/images/
  #   - assets/icons/
